version: "3.8"

services:
  backend:
    build: .
    container_name: chatbot-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/chatbot
    command: ["pnpm", "start"]
    networks:
      - chatbot-network

  postgres:
    image: postgres:14
    container_name: chatbot-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge